services:
  nats:
    image: nats:2-alpine
    restart: always
    ports:
      - '4222:4222'
    volumes:
      - ./nats_data:/data

  nats_jetstream:
    image: nats:2-alpine
    restart: always
    ports:
      - '4222:4222'
    command: -js
    volumes:
      - ./nats_jetstream_data:/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/server
    ports:
      - "8080:8080"
    depends_on:
      - nats

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/consumer
    depends_on:
      - nats

volumes:
  nats_data:
  nats_jetstream_data:
